import streamlit as st
import logging
import time
import json
import requests
import base64
from openai import OpenAI, OpenAIError
import pandas as pd
import PyPDF2  # Import this for PDF reading

# Streamlit Page Configuration
st.set_page_config(
    page_title="Problem Extractor",
    page_icon="imgs/lb.jpg",
    layout="wide",
    initial_sidebar_state="auto",
    menu_items={
        "Get help": "https://github.com/AdieLaine/Streamly",
        "Report a bug": "https://github.com/AdieLaine/Streamly",
        "About": """
            ## Problem Extractor
            ### Using AI to Identify Problems from PDFs

            The Problem Extractor accepts PDF documents and uses AI to generate problem summaries or insights.
        """
    }
)

# Streamlit Title
st.title("Problem Extractor")

def extract_text_from_pdf(pdf_file):
    """Extracts text from a PDF file."""
    text = ""
    pdf_reader = PyPDF2.PdfReader(pdf_file)
    for page in pdf_reader.pages:
        text += page.extract_text()
    return text

def run_ai_algorithm(text):
    """
    Insert your AI algorithm here to process the text extracted from the PDF.
    
    Parameters:
    - text: str, the extracted text from the PDF

    Returns:
    - result: str, the output generated by the AI algorithm
    """
    # For example, your AI algorithm could look like this:
    result = "Processed output of AI Algorithm"  # Replace this with actual algorithm logic
    # Add your AI processing code here
    return result

# PDF Upload
def main():
    uploaded_pdf = st.file_uploader("Upload a PDF file", type="pdf")

    if uploaded_pdf is not None:
        # Extract text from PDF
        st.info("Extracting text from PDF...")
        extracted_text = extract_text_from_pdf(uploaded_pdf)
        
        # Display extracted text (optional, for debugging)
        with st.expander("Extracted Text"):
            st.write(extracted_text)
        
        # Run AI algorithm on extracted text
        st.info("Running AI algorithm...")
        output = run_ai_algorithm(extracted_text)
        
        # Display AI-generated output
        st.subheader("AI-Generated Output")
        st.write(output)

if __name__ == "__main__":
    main()
